### SOLAR PARKS ###
@hostname = http://localhost:8080

### CONTACTS ###
## getAll() ###
GET  {{hostname}}/projects
### getById()
GET  {{hostname}}/projects/1
### getByProjectId()
GET  {{hostname}}/projects/customer/2
### create()
POST {{hostname}}/projects
Content-Type: application/json

{
    "name": "Solar electric 2",
    "cost": 123,
    "active": 1,
    "customer": 1,
    "contacts": [1,2]
}
### update()
PUT {{hostname}}/projects/1
Content-Type: application/json

{
    "name": "Solar electric 2",
    "cost": 123,
    "active": 1,
    "customer": 1,
    "contacts": [1]
}
### delete()
DELETE {{hostname}}/projects/2