### RENT a CAR ###
@hostname = http://localhost:8165

### CARS ###
## getById() ###
GET  {{hostname}}/cars/1
### getAllByCity()
GET  {{hostname}}/cars/user/Sofia
### create()
POST {{hostname}}/cars
Content-Type: application/json

{
  "brand": "BMW",
  "model": "3 Series",
  "city": "Varna",
  "year": 2020,
  "pricePerDay": 80.0
}

### update()
PUT {{hostname}}/cars/1
Content-Type: application/json

{
  "brand": "BMW",
  "model": "3 Series",
  "city": "Varna",
  "year": 2020,
  "pricePerDay": 80.0
}
### delete()
DELETE {{hostname}}/cars/2