### RENT a CAR ###
@hostname = http://localhost:8165

### CARS ###
## getById() ###
GET  {{hostname}}/offers/1
### getAllByCity()
GET  {{hostname}}/offers/users/1
### create()
POST {{hostname}}/offers
Content-Type: application/json

{
    "userId":2,
    "carId":2,
    "startDate": "2023-10-01",
    "endDate":"2023-10-05"
}
### acceptOffer()
PUT {{hostname}}/offers/5
Content-Type: application/json

### delete()
DELETE {{hostname}}/offers/2