### RENT a CAR ###
@hostname = http://localhost:8165

### USERS ###
## getById() ###
GET  {{hostname}}/users/5
### getAll()
GET  {{hostname}}/users
### create()
POST {{hostname}}/users
Content-Type: application/json

{
      "firstName": "Angel",
      "lastName": "Mladenov",
      "city": "Kavarna",
      "phone": "1122334455",
      "years": 40,
      "previousAccidents": false
}

### update()
PUT {{hostname}}/users/1
Content-Type: application/json

{
      "firstName": "Angel",
      "lastName": "Mladenov",
      "city": "Kavarna",
      "phone": "1122334455",
      "years": 40,
      "previousAccidents": false
}
### delete()
DELETE {{hostname}}/users/2